.TH termhelper 8  "2 апреля, 2021" "версия 0.2.*" "TERMHELPER"
.SH НАЗВАНИЕ
termhelper \- утилита для получения дополнительной помощи при работе в терминале 
.SH ОБЗОР
Справочная система для получения дополнительной иформации при работе в терминале
.TP
\- termhelper \- основная справка
.TP
\- termhelper раздел подраздел справка \- получение информации по разделу "справка"
.TP
\- cat file | termhelper \- ЭТО ЗАГОЛОВОК: \- вывести содержимое файла "file" как страницу справки с заголовком "ЭТО ЗАГОЛОВОК:" 
.SH КОД ЗАВЕРШЕНИЯ
.TP
\-  0 \- при удачном завершении termhelper
.TP
\- 127 \- всегда при обработке /etc/profile.d/termhelper.sh
.SH ФАЙЛЫ
.TP
\- /usr/bin/termhelper \- основной скрипт
.TP
\- /usr/share/termhelper/* \- каталог со справочными файлами
.TP
\- /etc/profile.d/termhelper.sh \- функция обрабатывающая ситуацию "command not found"
.SH АВТОР
Betkher Alexandr a.betkher@rosalinux.ru
.SH ЕЩЕ
man(1), info(1)
