#!/bin/sh
# POSIX-shell compatible functions for using
# from different parts of termhelper
# th means termhelper

black='\033[0;30m' 
red='\033[0;31m' 
green='\033[1;32m' 
yellow='\033[1;33m' 
brown='\033[0;33m'
blue='\033[0;34m' 
light_blue='\033[1;34m'
magenta='\033[1;35m'
cyan='\033[0;36m'
white='\033[0;37m' 
purple='\033[0;35m'
default='\033[0m'

_th_load_config(){
	for i in \
		/etc/termhelper.d/* \
		/run/termhelper.d/* \
		/etc/termhelper \
		$HOME/.config/termhelper.d/* \
		$HOME/.config/termhelper
	do
		test -e "$i" && . "$i"
	done
}

_th_gettext(){
	TEXTDOMAIN=termhelper \
	TEXTDOMAINDIR=/usr/share/locale \
	gettext -s "$@"
}
